version: '3.8'


networks:
  internal_network:
    driver: bridge

services:

  panel-app:
    # build:
    #   context: ./visualization
    image: matiascollado/frontend-panel-app:v1.0
    container_name: panel-app
    ports:
      - "5000:5000"
    volumes:
      - ../egi-control/data:/opt/airflow/data  # Compartimos los datos con la app
      - ./visualization:/app  # Compartimos la app con el contenedor

