version: '3.8'


networks:
  internal_network:
    driver: bridge

services:

   frontend:
    build:
      context: ./
    image: frontend-app-image
    container_name: frontend-app
    ports:
      - "3000:3000"
    networks:
      - internal_network
    environment:
      FLASK_ENV: development
      AIRFLOW_URL: http://airflow-webserver:8080
      PANEL_URL: http://panel-app:5000

