version: '3.8'


networks:
  internal_network:
    driver: bridge

services:

  panel-app:
    # build:
    #   context: ./visualization
    image: matiascollado/frontend-panel-app:v1.0
    container_name: panel-app
    ports:
      - "5000:5000"
    volumes:
      - ../control/data:/opt/airflow/data  # Compartimos los datos con la app
      - ./visualization:/app  # Compartimos la app con el contenedor

  # frontend:
  #   # build:
  #   #   context: ./
  #   image: 
  #   container_name: frontend-app
  #   ports:
  #     - "3000:3000"
  #   networks:
  #     - internal_network
  #   environment:
  #   - FLASK_ENV=development
  #   volumes:
  #   - ./frontend:/app
